#!/bin/dash

# disable bell
xset -b

# load xterm defaults
[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

# SET XDG_RUNTIME_DIR
mkdir /tmp/${USER}-runtime && chmod -R 0700 /tmp/${USER}-runtime
export XDG_RUNTIME_DIR=/tmp/${USER}-runtime

# TIMEZONE
TZ=America/Sao_Paulo

# START PROGRAMS
setxkbmap -model pc104 -layout us_intl &
/usr/bin/pipewire &
/usr/bin/pipewire-pulse &
#/usr/bin/wireplumber &
dwmblocks &
newlook &
#qbittorrent-nox &
#/opt/Radarr/Radarr -nobrowser &
#mono --debug /opt/Sonarr/Sonarr.exe &
#/opt/Prowlarr/Prowlarr -nobrowser &
#python3 /opt/bazarr/bazarr.py &
exec dbus-run-session dwm
